controller_names:
  - arm_controller

arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - arm_lower_joint
    - arm_mid_joint
    - arm_upper_joint
    - arm_wrist_joint
