controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_controller:
      type: diff_drive_controller/DiffDriveController

arm_controller:
  ros__parameters:
    joints:
      - arm_lower_joint
      - arm_mid_joint
      - arm_upper_joint
      - arm_wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

diff_controller:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['base_wheel_l_joint']
    right_wheel_names: ['base_wheel_r_joint']
    wheel_radius: 0.1
    wheel_separation: 0.38
    use_stamped_vel: false
