controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_l_controller:
      type: position_controllers/GripperActionController

    gripper_r_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - arm_lower_link_joint
      - arm_mid_link_joint
      - arm_upper_link_joint
      - arm_wrist_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      arm_lower_link_joint: { trajectory: 0.2, goal: 0.1 }
      arm_mid_link_joint  : { trajectory: 0.2, goal: 0.1 }
      arm_upper_link_joint: { trajectory: 0.2, goal: 0.1 }
      arm_wrist_link_joint: { trajectory: 0.2, goal: 0.1 }

gripper_l_controller:
  ros__parameters:
    joint: gripper_l_link_joint

gripper_r_controller:
  ros__parameters:
    joint: gripper_r_link_joint
