controller_names:
  - arm_controller
  - gripper_l_controller
  - gripper_r_controller

arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - arm_lower_joint
    - arm_mid_joint
    - arm_upper_joint
    - arm_wrist_joint

gripper_l_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - gripper_l_joint

gripper_r_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - gripper_r_joint
