controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_l_controller:
      type: position_controllers/GripperActionController

    gripper_r_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - arm_lower_joint
      - arm_mid_joint
      - arm_upper_joint
      - arm_wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_l_controller:
  ros__parameters:
    joint: gripper_l_joint

gripper_r_controller:
  ros__parameters:
    joint: gripper_r_joint
